### PR TITLE
Compatibility with Sonar 10 and 9.5+

### LINKED ISSUE #373: Sonarqube Version 10.0 Compatibility
When I install the plugin and click on More License Check, I get a blank screen.

Screenshot 2023-05-03 at 4 36 49 PM

### PR DESCRIPTION
**Pull request by fvclaus**
Fixes #373

I tested with Sonarqube 10.1, but this should with Sonar 9.5+, because this is the plugin API dependency version that I use. For the 10.x release there haven't been any breaking changes so the plugin API is still using 9.x. 9.5 was the first release were the plugin API was released separately, that's why I choose that version. There is a good chance that this will work with 9.0 - 9.4 as well.

I removed some deprecated classes that did not compile anymore. The frontend wasn't working because of the stricter CSP header that does not allow Vue.js `template` strings.

### CODE REVIEW

**Comment by fvclaus** [comment]
This is what broke this plugin:

image

https://docs.sonarqube.org/latest/setup-and-upgrade/release-upgrade-notes/

**Comment by fvclaus** [comment]
@derkoe can you please take a look at this?

**Comment by derkoe** [comment]
Just tried this with SonarQube 10.1 - still shows a blank screen. Nothing in the console log.

image

**Comment by fvclaus** [comment]
> Just tried this with SonarQube 10.1 - still shows a blank screen. Nothing in the console log.
> 
> image

This is what I said in the mail. The administration is still broken, because of the CSP violation. I only touched the dashboard. Up until yesterday, I didn't even know how to get to the administration page, until another user pointed out to me that it is still broken.

**Comment by fvclaus** [comment]
@derkoe I fixed the administration page:

image

You might need to reload with Ctrl+Shift+R to bypass the cached version of the old version.

**Review by derkoe — APPROVED** [review]

**Comment by derkoe** [comment]
Now, we only have to figure out a way to bootstrap the data (mostly SPDX licenses)

**Pull request merged**
