### PR TITLE
update documentation

### PR DESCRIPTION
**Pull request by Janpopan**
This removes the old config pages and updates the documentation

### CODE REVIEW

**Review by derkoe — CHANGES_REQUESTED** [review]
Why delete the current UI? configuration.js, dashboard.js and all the vue files are the current UI

**Comment by Janpopan** [comment]
Because, now there are 2 implementaions in the code with the same functionality.
Also 2 points to toggle the plugin on or off. 

Maybe it is better to bring both together - like the Sonar-ALM page. Or also put the project-specific setting to an per-project menu.

We try to use the plugin in more than 300 projects. So I get a lot of feedback.

But I can make 2 PRs - one for documentation and one for the radical step ;-)

**Comment by derkoe** [comment]
You are deleting all frontend files - I'm not sure where you find the second implementation

**Comment by Janpopan** [comment]
with the PR I "only" removed the "old" config menu. The dashboard is not removed.
You did the implemation of the "new" config menu by your self.
You can see it in the documentation screenshots.

**Comment by Janpopan** [comment]
> You delete:
> 
> * src/main/web/configuration.js
> * src/main/web/configuration/dependency-mappings-page.vue
> * src/main/web/configuration/license-mappings-page.vue
> * src/main/web/configuration/licenses-page.vue
> * src/main/web/configuration/project-licenses-page.vue
> * src/main/web/configuration/sonar-api.js

Yes - I am aware of this.

> This is the whole configuration frontend. 

Yes - I am aware of this.

> This frontend is still in use an recommended to use.

Ok - but you have now two frontends for the same thing - with diferent startpoints
 
> The native version does not have selects and does not check for integrity.

Ok - I was not aware of this point

so my "solution" is not a good thing.


So I will do a separate PR for the documentation. And open some tickets with question about UX:
- "Global" Admin UI
- CI/CD parameters
- API parameters
- "project" Admin UI
- ...
:-)

**Comment by Janpopan** [comment]
I will try a new one

**Pull request closed without merging**
